# default configuration
baseURL = "https://wulinginfor.tk/"
languageCode = "en-us"
summaryLength = "5"
theme = "kross"
title = "武陵資讀"

# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/font-awesome/css/all.min.css"

# js plugin
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"


# menu
# [[menu.main]]
# URL = "about"
# name = "關於武陵資讀"
# weight = 1


[[menu.main]]
URL = "announcement"
name = "公告"
weight = 1

# [[menu.main]]
# URL = "portfolio"
# name = "Portfolio"
# weight = 3

[[menu.main]]
URL = "register"
name = "報名"
weight = 2

[[menu.main]]
URL = "http://wloj.wlsh.tyc.edu.tw/"
name = "WLOJ"
weight = 3
parent = "站外連結"

[[menu.main]]
URL = "https://discord.gg/aDuj8HEyTn"
name = '武陵資讀 Discord'
weight = 4
parent = "站外連結"

# default parameters
[params]
home = "首頁"
logo = "images/logo.png"
# theme color
theme_color = "#004266"
# contact info
# phone = "+880 2544 658 256"
# email = "wuling.infor@gmail.com"
# address = "125/A, CA Commercial Area, California, USA"
# meta description
author = "管理員"
description = "武陵高中資訊讀書會網站"
# google analytics
google_analytics_id = "" # Your ID
# copyright
copyright = "聯絡信箱：wuling.infor@gmail.com | Copyright &copy; 2020 a theme by [gethugothemes](https://gethugothemes.com)"


# preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif" # use png, jpg, svg or gif format

# contact
[params.contact]
enable = false
form_action = "https://formspree.io/f/moqylpzw" # contact form works with : https://formspree.io

# google map
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=&#038;types=(cities)&#038;libraries=places&#038;language=en"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"

# cookies
[params.cookies]
enable = true
expire_days = 2

# social site
# [[params.social]]
# icon = "ti-facebook"
# URL = "#"

# [[params.social]]
# icon = "ti-instagram"
# URL = "#"

# [[params.social]]
# icon = "ti-dribbble"
# URL = "#"

# [[params.social]]
# icon = "ti-twitter-alt"
# URL = "#"

# [[params.social]]
# icon = "fab fa-discord"
# URL = "https://discord.gg/aDuj8HEyTn"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = "github"
      [markup.goldmark.parser.attribute]
        block = false
        title = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false